version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly' # or "daily" or "monthly"
      allow:
          - update-type: 'version-update:semver-major'
