name: Build and Upload to Launchpad PPA

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
      LAUNCHPAD_PASSWORD: ${{ secrets.LAUNCHPAD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq devscripts debhelper dh-make dput gnupg lintian build-essential

      - name: Extract package info from package.json
        id: package_info
        run: |
          echo "PACKAGE_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          DESCRIPTION=$(jq -r '.description' package.json)
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV
          echo "MAINTAINER_EMAIL=${{ secrets.LAUNCHPAD_USERNAME }}" >> $GITHUB_ENV

      - name: Prepare debian directory and control files
        run: |
          rm -rf debian
          mkdir -p debian

          cat > debian/control << EOF
Source: $PACKAGE_NAME
Section: utils
Priority: optional
Maintainer: Oblivion Desktop <$MAINTAINER_EMAIL>
Build-Depends: debhelper (>= 12), build-essential
Standards-Version: 4.5.1
Homepage: https://github.com/bepass-org/oblivion-desktop

Package: $PACKAGE_NAME
Architecture: any
Depends: \${shlibs:Depends}, \${misc:Depends}
Description: $DESCRIPTION
EOF

          DATE=$(date -R)
          cat > debian/changelog << EOF
$PACKAGE_NAME ($VERSION) unstable; urgency=medium

  * Initial release.

 -- Oblivion Desktop <$MAINTAINER_EMAIL>  $DATE
EOF

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import private.key
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgsign true
          git config --global user.name "Oblivion Desktop"
          git config --global user.email "$MAINTAINER_EMAIL"

      - name: Build source package
        run: debuild -S -sa -k$GPG_KEY_ID

      - name: Sign source package files
        run: |
          gpg --batch --yes -u "$GPG_KEY_ID" --armor --detach-sign ${PACKAGE_NAME}_${VERSION}_source.changes
          gpg --batch --yes -u "$GPG_KEY_ID" --armor --detach-sign ${PACKAGE_NAME}_${VERSION}.dsc

      - name: Upload to Launchpad PPA
        run: dput ppa ${PACKAGE_NAME}_${VERSION}_source.changes
