name: Build and Release to Launchpad PPA

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
      LAUNCHPAD_PASSWORD: ${{ secrets.LAUNCHPAD_PASSWORD }}
      PACKAGE_NAME: "oblivion-desktop"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq devscripts debhelper dh-make dput gnupg lintian

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare debian directory with dh_make
        run: |
          rm -rf debian
          dh_make --createorig -s -y -p ${PACKAGE_NAME}_${VERSION}
          
          sed -i "1s/.*/${PACKAGE_NAME} (${VERSION}) unstable; urgency=medium\n\n  * Initial release from GitHub Actions.\n\n -- Oblivion Desktop <${{ secrets.LAUNCHPAD_USERNAME }}>  $(date -R)/" debian/changelog

      - name: Setup GPG for signing
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import private.key
          gpg --list-secret-keys --keyid-format LONG
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgsign true
          git config --global user.name "Oblivion Desktop"
          git config --global user.email "${{ secrets.LAUNCHPAD_USERNAME }}"

      - name: Build source package
        run: |
          debuild -S -sa -k$GPG_KEY_ID

      - name: Sign source package files
        run: |
          gpg --batch --yes -u "$GPG_KEY_ID" --armor --detach-sign ${PACKAGE_NAME}_${VERSION}_source.changes
          gpg --batch --yes -u "$GPG_KEY_ID" --armor --detach-sign ${PACKAGE_NAME}_${VERSION}.dsc

      - name: Upload source package to Launchpad PPA
        run: |
          dput ppa ${PACKAGE_NAME}_${VERSION}_source.changes
