name: Release to PPA

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
      LAUNCHPAD_PASSWORD: ${{ secrets.LAUNCHPAD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read version from package.json and copy to versioned directory
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          PACKAGE_NAME="oblivion-desktop"
          DIR_NAME="${PACKAGE_NAME}-${VERSION}"
          cp -r . "../$DIR_NAME"
        shell: bash

      - name: Set up GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import private.key
          gpg --list-secret-keys --keyid-format LONG
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgsign true
          git config --global user.name "oblivion-desktop"
          git config --global user.email "${{ secrets.LAUNCHPAD_USERNAME }}"

      - name: Install packaging tools
        run: |
          sudo apt update
          sudo apt install -y build-essential devscripts debhelper dh-make dput gnupg lintian jq

      - name: Create debian directory structure with dh_make
        run: |
          if [ ! -d debian ]; then
            dh_make --createorig -s -y -p oblivion-desktop_${{ env.VERSION }}
          fi
        working-directory: ../oblivion-desktop-${{ env.VERSION }}

      - name: Update changelog file
        run: |
          sed -i "1s/^/oblivion-desktop (${VERSION}) unstable; urgency=medium\n\n  * Initial release.\n\n -- Oblivion Desktop <${{ secrets.LAUNCHPAD_USERNAME }}>  $(date -R)\n\n/" debian/changelog
        working-directory: ../oblivion-desktop-${{ env.VERSION }}

      - name: Build .deb package
        run: dpkg-buildpackage -us -uc
        working-directory: ../oblivion-desktop-${{ env.VERSION }}

      - name: List files after build (for debug)
        run: ls -l ../
      
      - name: Sign .changes and .dsc files
        run: |
          VERSION=$(dpkg-parsechangelog --show-field Version)
          PACKAGE_NAME="oblivion-desktop"
          DIR_NAME="${PACKAGE_NAME}-${VERSION}"
          cd ../
          DEB_CHANGES=$(ls ${DIR_NAME}/*${VERSION}_source.changes)
          gpg --batch --yes -u "$GPG_KEY_ID" --armor --detach-sign ${DIR_NAME}/*.dsc
          gpg --batch --yes -u "$GPG_KEY_ID" --armor --detach-sign "$DEB_CHANGES"
        shell: bash

      - name: Upload to Launchpad PPA
        run: |
          VERSION=$(dpkg-parsechangelog --show-field Version)
          PACKAGE_NAME="oblivion-desktop"
          DIR_NAME="${PACKAGE_NAME}-${VERSION}"
          dput ppa ${DIR_NAME}/*source.changes
        shell: bash
