name: Release to PPA

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
      LAUNCHPAD_PASSWORD: ${{ secrets.LAUNCHPAD_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read version from package.json and rename directory
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version found: $VERSION"
          PACKAGE_NAME="oblivion-desktop"
          DIR_NAME="${PACKAGE_NAME}-${VERSION}"
          mv "$(pwd)" "$(dirname "$(pwd)")/$DIR_NAME"
          cd "$(dirname "$(pwd)")/$DIR_NAME"
          echo "Renamed directory to $DIR_NAME"
        shell: bash

      - name: Set up GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import private.key
          gpg --list-secret-keys --keyid-format LONG
          git config --global user.signingkey "$GPG_KEY_ID"
          git config --global commit.gpgsign true
          git config --global user.name "oblivion-desktop"
          git config --global user.email "${{ secrets.LAUNCHPAD_USERNAME }}"

      - name: Install packaging tools
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper dh-make dput gnupg lintian

      - name: Create debian directory structure with dh_make
        run: |
          if [ ! -d debian ]; then
            dh_make --createorig -s -y -p oblivion-desktop_${VERSION}
          fi

      - name: Update changelog file
        run: |
          sed -i "1s/^/oblivion-desktop (${VERSION}) unstable; urgency=medium\n\n  * Initial release.\n\n -- Oblivion Desktop <${{ secrets.LAUNCHPAD_USERNAME }}>  $(date -R)\n\n/" debian/changelog

      - name: Build .deb package
        run: dpkg-buildpackage -us -uc
        working-directory: .
